"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let orange = "orange";
let upperCaseApple = "APPLE";
let ten = 10;
let fifty = 50;
let fruits = ["mango", "orange", "banana"];
console.log("check equality and inequality");
console.log(orange == "orange");
console.log(orange != orange);
// tests using lowercase function //
console.log("FOR LOWERCASE FUNCTION");
console.log(upperCaseApple.toLowerCase() == "apple");
console.log(upperCaseApple.toLowerCase() != "apple");
// Numerical tests //
console.log("for numerical value ");
console.log(ten == 10);
console.log(ten != 10);
console.log(fifty > ten);
console.log(fifty < ten);
console.log(fifty >= ten);
console.log(fifty <= ten);
console.log(' using and or operators');
console.log(fifty != 10 && fifty > 10);
console.log(fifty != 10 && ten > fifty);
console.log(fifty < ten || fifty == 50);
console.log(ten > fifty || fifty == ten);
console.log("using  array");
console.log(fruits.includes("orange"));
console.log(!fruits.includes("orange"));
